title: "Cyberaddiction in Latin America: Database by Age Groups and "
description: "Database on cyberaddiction (internet, social media and video game addiction) in Latin America, with statistics organized by age groups (children, adol"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/cyberaddiction-in-latin-america-database-by-age-groups-and-countries-2018-2024"
